# Generated by Django 2.2.12 on 2023-10-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osaka_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionlist',
            old_name='title_addrss',
            new_name='title_address',
        ),
    ]
